### ISSUE TITLE
NEW LOGO

### ISSUE THREAD

**Issue by rijal10** [heiswayi/mit-license#1]
Hello heiswayi.
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by heiswayi** [comment]
what kind of logo?

**Comment by rijal10** [comment]
May I know what kind of logo @heiswayi wants?

**Comment by rijal10** [comment]
yes of course this is related to your application I will make it with elegant variations! may I make it?

**Comment by heiswayi** [comment]
logo is not necessary for project like this... mit-license (this repo) is just stupidly simple stuff. i think it's too overkill for a logo.

**Comment by rijal10** [comment]
I am sorry! if you have a new project just say to me! i will do it yag best for you!

**Comment by rijal10** [comment]
thank!

**Comment by rijal10** [comment]
I am sorry! if you have a new project just say to me! I will do my best for you!

**Comment by rijal10** [comment]
thank!
